#Requires AutoHotkey v2.0

; Generated by Auto-GUI 3.0.1
#SingleInstance Force
; V1toV2: Removed #NoEnv
SetWorkingDir(A_ScriptDir)
; V1toV2: Removed SetBatchLines -1

myGui := Gui()
myGui.OnEvent("Close", GuiEscape)
myGui.OnEvent("Escape", GuiEscape)
myGui.SetFont("s9", "Segoe UI")
myGui.SetFont()
myGui.SetFont("s20", "Segoe UI")
myGui.Add("Text", "x8 y8 w482 h41 +0x200", "Text")
myGui.SetFont()
myGui.SetFont("s9", "Segoe UI")
ogcButtonOK := myGui.Add("Button", "x494 y8 w176 h49", "&OK")
myGui.Add("Text", "x-8 y55 w503 h2 +0x10")
myGui.Add("Text", "x8 y63 w97 h26 +0x200", "Button:")
myGui.Add("ComboBox", "x109 y64 w120", ["Left", "Right", "Middle", "Key"])
myGui.Add("Hotkey", "x232 y64 w120 h24")
myGui.Add("Radio", "x360 y64 w130 h28", "Single Click")
myGui.Add("Radio", "x496 y64 w160 h26", "Double Click")
myGui.Add("Text", "x7 y104 w150 h23 +0x200", "Start/Stop Hotkey:")
myGui.Add("Radio", "x8 y145 w147 h23", "Unlimited")
myGui.Add("Radio", "x161 y146 w102 h23", "Stop after:")
myGui.Add("Radio", "x400 y148 w89 h23", "Stop after:")
myGui.Add("Edit", "x264 y147 w63 h21")
myGui.Add("Text", "x329 y147 w61 h23 +0x200", "clicks")
myGui.Add("Edit", "x490 y150 w63 h21")
myGui.Add("Text", "x555 y150 w61 h23 +0x200", "sec")
myGui.Add("Text", "x-6 y176 w736 h0 +0x10")
myGui.Add("Radio", "x8 y192 w289 h23", "All windows")
myGui.Add("Radio", "x8 y223 w288 h23", "Only click on selected window")
myGui.Add("Radio", "x8 y256 w290 h23", "Hidden Click on selected window")
myGui.Add("Text", "x320 y194 w337 h23 +0x200 +Center", "Select Window")
myGui.Add("ComboBox", "x320 y224 w257", ["ComboBox"])
ogcButtonRefresh := myGui.Add("Button", "x584 y225 w73 h23", "Refresh")
myGui.Add("Hotkey", "x159 y103 w50 h26")
myGui.Add("CheckBox", "x8 y296 w129 h23", "Click at position")
myGui.Add("Text", "x148 y296 w27 h23 +0x200", "X:")
myGui.Add("Edit", "x176 y296 w74 h25")
myGui.Add("Text", "x271 y296 w27 h23 +0x200", "Y:")
myGui.Add("Edit", "x299 y296 w74 h25")
ogcButtonGetMousePosition := myGui.Add("Button", "x375 y295 w139 h28", "Get Mouse Position")
myGui.Add("CheckBox", "x8 y335 w120 h23", "Auto Stop")
myGui.Add("Text", "x132 y337 w120 h23 +0x200", "What is Auto Stop?")
myGui.Add("Text", "x359 y104 w120 h23 +0x200", "Click Speed (ms):")
myGui.Add("Edit", "x480 y104 w67 h25")
ogcButtonSavethisconfig := myGui.Add("Button", "x7 y376 w306 h25", "Save this config")
ogcButtonLoadasavedconfig := myGui.Add("Button", "x328 y376 w336 h25", "Load a saved config")

myGui.Title := "Window"
myGui.Show("w681 h466")
Return

GuiEscape(*)
{ ; V1toV2: Added bracket
global ; V1toV2: Made function global
GuiClose:
    ExitApp()
} ; V1toV2: Added bracket in the end
